name: Java Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1  # Use version 2 of the action
      with:
        java-version: 17  # Change to Java 17

    - name: Compile Java code
      run: |
        mvn package  # Use the Maven compile command
      working-directory: ./futuionsales

    - name: AWS ECR Login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 359658559307.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t javabkpp .
        docker tag javabkpp:latest 359658559307.dkr.ecr.ap-south-1.amazonaws.com/javabkpp:latest
	      docker push 359658559307.dkr.ecr.ap-south-1.amazonaws.com/javabkpp:latest
  
 
