name: Java Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Compile Java code
      run: |
        mvn package
      working-directory: ./futuionsales

    - name: AWS ECR Login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 359658559307.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        # Generate a unique tag based on the run number and timestamp
        TAG="$(date +'%Y%m%d%H%M%S')-$GITHUB_RUN_NUMBER"
        docker build -t javabkpp:$TAG .
        docker tag javabkpp:$TAG 359658559307.dkr.ecr.ap-south-1.amazonaws.com/javabkpp:$TAG
        docker push 359658559307.dkr.ecr.ap-south-1.amazonaws.com/javabkpp:$TAG
      working-directory: ./futuionsales 

      #test1
